### ISSUE TITLE
[support] Failed Redeem Process, AVAX to Algorand <ticket-7614>

### ISSUE THREAD

**Issue by drisAloma** [XLabs/portal-bridge-ui#313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain: Avalanche
- Source Chain Wallet:0x36882bbf0e7c5d7d750e78148351e7beee766d2d
- Target Chain: Algorand
- Target Chain Wallet: OE3E3L3Y3Z5JDCPN3ZEIF7NBDSYACA7ZQUFKMHPUO3ELCCFE7EDMGRNKBQ
- Asset Type: Token
- Token : AVAX
- VPN : No
- Tx: 0x58c516967baca878af60736c830ecae715f69ae85e62467f7063e867483678c4
```

### Current Behavior

After clicking on the redeem button, it throws **"Network request error. Requested status 400 ()"** after loading for a while.

![ledger_avax_algo](https://github.com/XLabs/portal-bridge-ui/assets/64994788/8ff126ed-2b70-4718-a398-ff3c572830dd)
![desktop_avax_algo](https://github.com/XLabs/portal-bridge-ui/assets/64994788/d48ae119-d15a-4168-bfe5-c200a15dec13)

### Steps To Reproduce

Redeem workflow

### Anything else?

The user tried on ledger and pera mobile wallet. There is no option to enable blind signing.

**Comment by sebastianscatularo** [comment]
does the user have enough funds in his Algorand wallet?

**Comment by dry2022** [comment]
Hello! User is still having problem. 
"After I confirm the TX via my ledger I get the 400 error in the screencap above"

**Comment by dry2022** [comment]
Any alternatives for him? :)

**Comment by SamantaCasal** [comment]
FYI: @hernandiegosavio: 
1 _**When simulating the transaction**_ (Send Avax from Avalanche to Algorand using Metamask/PeraWallet) in step 4 Redeem the error "Transaction not confirmed after 4 rounds" is displayed
2 **_When trying to redeem manually_**, it shows the message that the token has already been redeemed, which is correct.
Whereby:

- Verified that there is apparently a UI error when sending AVAX from Avalanche -> Algorand using the Meta/Pera wallet.
- It is verified that the transaction is carried out successfully, that is, it is already redeemed. [snowtrace](https://snowtrace.io/tx/0xfe9824deb8f0fbfec07c8f75fc46c004ae010c44d15301713711f57b429047e4) [algoExplorer](https://algoexplorer.io/tx/2CYFAJX45RWQGNTISILIF33XKLGEYNLAOLE5KRZAD2I6C2WNG3LA)

Regarding the user's tx, it looks available to redeem 0x58c516967baca878af60736c830ecae715f69ae85e62467f7063e867483678c4 at https://www.portalbridge.com/#/redeem
Evidence: 
1 Making  the transfer

https://github.com/XLabs/portal-bridge-ui/assets/69044575/84847e24-b985-4c8d-8992-bbc5cc65c6dd

2 Redeem 

https://github.com/XLabs/portal-bridge-ui/assets/69044575/c67c88dd-ffa6-4c08-978f-9ddcb0b103ee

**Comment by SamantaCasal** [comment]
I leave it on ALL so that the error mentioned above is corrected. FYI: @hernandiegosavio

**Comment by Dahtank** [comment]
Please note that the user is using Ledger on Pera wallet
Currently, his TX 0x58c516967baca878af60736c830ecae715f69ae85e62467f7063e867483678c4 still shows "Network Request Error Received status 400" while trying to redeem

**Comment by SamantaCasal** [comment]
FYI: @yuli-ferna the UI issue is fixed, but when I try to redeem the user TX ID: 0x58c516967baca878af60736c830ecae715f69ae85e62467f7063e867483678c4 still shows `"Network Request Error Received status 400"`
Tested from: https://preview.portalbridge.com/305ff71a2e/#/transfer
Evidence: 

https://github.com/XLabs/portal-bridge-ui/assets/69044575/b8cf56d7-7d9f-4ac2-b41e-6d99801a4564

![Screenshot 2023-09-18 at 4 57 22 PM](https://github.com/XLabs/portal-bridge-ui/assets/69044575/7611ca90-256b-496e-9e2b-eb49b19731ef)

**Comment by dry2022** [comment]
hello! 
![image](https://github.com/XLabs/portal-bridge-ui/assets/102968460/07f693c9-6ec9-4d2c-a95c-a962998e12d5)

what can we suggest for this user :)?

**Comment by SamantaCasal** [comment]
FYI: @dry2022 @Dahtank 
**Update of the case of the user who made the `TX: 0x58c516967baca878af60736c830ecae715f69ae85e62467f7063e867483678c4.`**

@yuli-ferna has redeemed that transaction with an advanced version of the SDK, [ALGOEXPLORERView](https://algoexplorer.io/tx/L36564DZX7PQPDLO2IXRPQJEB4Z7FBSLUTNID7EWSI3QUQQOARFQ.)
We are not yet ready to upload that version to prod, but we will surely do so in the future. Please indicate to the user that until then they will not be able to redeem this type of txs.

**Evidence:** 

![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/f67b82fb-f4ea-4ab4-8566-ea92031ce509)

**Comment by drisAloma** [comment]
Noted! @SamantaCasal 
Thank you.

**Comment by drisAloma** [comment]
Quick question @SamantaCasal 
Does that mean any transaction from Avalanche -> Algorand cannot be redeemed manually at this time or did the user do something different!?

**Comment by yuli-ferna** [comment]
@drisAloma for now we cannot guarantee that the Avalanche -> Algorand transaction will be redeemed correctly without the error from before, we are working to bring the update.

**Comment by drisAloma** [comment]
Okay noted
Thank you! @yuli-ferna

**Comment by SamantaCasal** [comment]
@yuli-ferna tested from https://preview.portalbridge.com/addd1f8564/#/transfer
I was able to carry out successfully the following transactions: 
Send AVAX from Avalanche -> Algorand 
Wallets: Metamask/Pera Mobile 
Let's leave this ticket open until after the deployment to prod, to re-test the case. 
[snowtrace](https://snowtrace.io/tx/0x6f086c718776f1c7b6591fb5661a7e0afb8ce7a81f4473de0a3a117fe01767be)
[algoexplorer](https://algoexplorer.io/tx/MBPUWQA5U2RXXQNB56MDO3RAVKHVVN5ANCGQPY4QFW7CZOU6YWLQ)
Evidence: 

https://github.com/XLabs/portal-bridge-ui/assets/69044575/cd447c99-7d11-4baf-b317-dddc8ed3ee51

**Comment by drisAloma** [comment]
I learnt a fix has been deployed and the bridging route is stable now @yuli-ferna @SamantaCasal 
Thanks guys!!🤝
