### ISSUE TITLE
[support] unable to redeem Injective -> Optimism (Ticket #11110）

### ISSUE THREAD

**Issue by willis20188** [XLabs/portal-bridge-ui#576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain:Injective
- Source Chain Wallet:inj1z4sraenzyh2t9yx3m38nmnnywgjlhc35jdcf63
- Target Chain:Optimism
- Target Chain Wallet:0x15603eE66225D4B290D1dC4F3Dce647225fBE234
- Asset Type:WETH
- Tx:https://explorer.injective.network/transaction/72021ca4669da92386d906837933e7221dc1b5b70c2202e76a55118fb9ba9008/
```

### Current Behavior

redeem workflow
Error message: cannot estimate gas
![image](https://github.com/XLabs/portal-bridge-ui/assets/83527164/9b34469d-3b7b-481c-b3ca-5a4b9a4bbe47)

**Comment by sebastianscatularo** [comment]
this should be fixed now as part of https://github.com/XLabs/portal-bridge-ui/pull/592

**Comment by willis20188** [comment]
Hello @sebastianscatularo 
The issue is not resolved and still persists

**Comment by sebastianscatularo** [comment]
@willis20188 @drisAloma I'm seeing two different issues with two different tx:

### first one -> Injective to Optimism
https://explorer.injective.network/transaction/72021ca4669da92386d906837933e7221dc1b5b70c2202e76a55118fb9ba9008/

could you get more info on what app/ui/bridge experience the user has used to start the transaction? checking, the emitter address is not the token bridge contract.

<img width="773" alt="image" src="https://github.com/XLabs/portal-bridge-ui/assets/1277510/5270e8c8-74dd-427c-8071-fbf9d104ef27">

the issue could be because the user has used a different bridge, that has their contract, could you verify the bridging experience that the user has used? also, @SamantaCasal could you try to reproduce it?

### second one -> Aptos to Optimism

on the other side, the Aptos to Optimism emitter address seems to be correct, so, there is something else happening

https://wormholescan.io/#/tx/0xaffc1cbf7d29741aede2d7393bd3788af9d4df1c6573e293fa1c542087ddba77

<img width="769" alt="image" src="https://github.com/XLabs/portal-bridge-ui/assets/1277510/2da0c746-9c0e-4b05-ba0c-ef0ea3833ea9">

**Comment by willis20188** [comment]
The user uses Portal Bridge
![image](https://github.com/XLabs/portal-bridge-ui/assets/83527164/bb773905-976a-48bb-8650-d090b338f3e1)

**Comment by drisAloma** [comment]
Yeah, they both seems to have similar redemption issue on Optimism (Internal JSON-RPC error) Another user is having the same issue (Solana to Optimism).
Should I log them in another ticket? @sebastianscatularo

**Comment by willis20188** [comment]
Hello
Is there any update on this?

**Comment by SamantaCasal** [comment]
Hi! 
Regarding the **first case INJ -> Optimism**
I can't reproduce the error because I can't select the native token and the nonnative tokens don't show, so I couldn't try sending from Injective. There is something that I can do to see my nonnative tokens or select the native one? 

![Screenshot 2023-12-30 at 11 13 07 AM](https://github.com/XLabs/portal-bridge-ui/assets/69044575/c178493e-b26c-493c-b21d-f2137d307a80)

Regarding the second one **APTOS -> OPTIMISM:** I don't have any problems redeemed tokens transferred, please see the following video. 


https://github.com/XLabs/portal-bridge-ui/assets/69044575/200a8f00-a621-409e-b1ef-407068737a60

**Comment by willis20188** [comment]
> Hi! Regarding the **first case INJ -> Optimism** I can't reproduce the error because I can't select the native token and the nonnative tokens don't show, so I couldn't try sending from Injective. There is something that I can do to see my nonnative tokens or select the native one?
> 
> ![Screenshot 2023-12-30 at 11 13 07 AM](https://private-user-images.githubusercontent.com/69044575/293464761-c178493e-b26c-493c-b21d-f2137d307a80.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5OTEyMzEsIm5iZiI6MTcwMzk5MDkzMSwicGF0aCI6Ii82OTA0NDU3NS8yOTM0NjQ3NjEtYzE3ODQ5M2UtYjI2Yy00OTNjLWIyMWQtZjIxMzdkMzA3YTgwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDAyNDg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNjVhYWZjZjE4ODU2MGZlODA3ZDQ1NmY1NzIwMjM4NjVmOTQxNDllNzIxNzk1Mjg4YWUxZTBhYjA5OTI2ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NUvn90EMr1MuAMkElu-xYk2fHTRd3W1ONjQfwZLae0k)
> 
> Regarding the second one **APTOS -> OPTIMISM:** I don't have any problems redeemed tokens transferred, please see the following video.
> 
>  Screen.Recording.2023-12-30.at.11.20.23.AM.mov

Hello
Paste the contract address: inj1plsk58sxqjw9828aqzeskmc8xy9eu5kppw3jg4
![image](https://github.com/XLabs/portal-bridge-ui/assets/83527164/ce40ea7a-b2aa-4d87-925e-7c1c610cabee)

**Comment by SamantaCasal** [comment]
Hi! Regarding the first case, we saw that the error is https://docs.ethers.org/v5/troubleshooting/errors/#help-UNPREDICTABLE_GAS_LIMIT. So, one possible solution is give to the user a set manual `gas limit`  option for the transaction. We will work in this improvement. 
@yuli-ferna 

![Screenshot 2024-01-02 at 11 12 29 AM](https://github.com/XLabs/portal-bridge-ui/assets/69044575/31e2eb2a-bd55-44c3-aa9f-a79f7080a634)

**Comment by sleepycorgi1** [comment]
> Hi! Regarding the first case, we saw that the error is https://docs.ethers.org/v5/troubleshooting/errors/#help-UNPREDICTABLE_GAS_LIMIT. So, one possible solution is give to the user a set manual `gas limit` option for the transaction. We will work in this improvement. @yuli-ferna
> 
> ![Screenshot 2024-01-02 at 11 12 29 AM](https://private-user-images.githubusercontent.com/69044575/293710346-31e2eb2a-bd55-44c3-aa9f-a79f7080a634.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTI1NDgsIm5iZiI6MTcwNDc5MjI0OCwicGF0aCI6Ii82OTA0NDU3NS8yOTM3MTAzNDYtMzFlMmViMmEtYmQ1NS00NGMzLWFhOWYtYTc5ZjcwODBhNjM0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA5MjQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMDhjZWIxOGJkZGUxZDc4Y2U2YzM3YTM5NzBjYmE1NDEwN2E5YmY0NWZlZjI0NmYxYWZjMTc0MWQzZTg4Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5-RjAZWarlGJFZLWyHt-HQkRpOy_rYJgttQT5mPDn58)

Thanks for looking into this Samanta , i've asked the user to try setting the gas limit but the error pops up as soon as they click redeem...

**Comment by yuli-ferna** [comment]
Yes, this is a problem to be solved from our side, we will notify you when there is no error.

**Comment by drisAloma** [comment]
Hello @sebastianscatularo 
Thank you.
Two of the users were able to redeem the transfer via the advanced VAA option but it still returns "There was an issue while fetching transaction details" error when the transaction hash is pasted 
![IMG_20240124_224906](https://github.com/XLabs/portal-bridge-ui/assets/64994788/548af4f5-0840-4374-ac8c-a0eff2c9355e)
directly

**Comment by sebastianscatularo** [comment]
@drisAloma that does not seems to be a valid tx hash
