### ISSUE TITLE
[support] Cannot Redeem to Algorand <ticket- 11290>

### ISSUE THREAD

**Issue by drisAloma** [XLabs/portal-bridge-ui#610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com/advanced-tools

### Bridge Experience URL

https://portalbridge.com/advanced-tools/#/redeem

### Operation Details

```markdown
- Source Chain: Polygon 
- Source Chain Wallet: Metamask 
- Target Chain: Algorand 
- Target Chain Wallet: Pera
- Asset Type:Token
- Tx:https://polygonscan.com/tx/0x0c9149c74958f0fb2e20e85daf37daec3b0c6f66ee23a577d1ce301041182d6b
```

### Current Behavior

Redeem process failed with the error in the ikage
![screenshot_OK](https://github.com/XLabs/portal-bridge-ui/assets/64994788/5d8c0024-a076-41df-a20f-e3fa9a7a76a7)

### Expected Behavior

Submit  Redeem Transaction Successfully 

### Steps To Reproduce

1. Go to https://portalbridge.com/advanced-tools/#/redeem
2. Choose polygon as the source chain 
3. Paste in the transaction hash: https://polygonscan.com/tx/0x0c9149c74958f0fb2e20e85daf37daec3b0c6f66ee23a577d1ce301041182d6b
4. Click Recover
5. Connect Algorand Pera wallet and click Redeem.
6. Approval redeem transaction in the wallet prompt

**Comment by SamantaCasal** [comment]
FYI: 
![Uploading 2DE6C41D-704F-4061-AF24-EDAAB9DF9C8F.PNG…]()

**Comment by SamantaCasal** [comment]
![2DE6C41D-704F-4061-AF24-EDAAB9DF9C8F](https://github.com/XLabs/portal-bridge-ui/assets/69044575/ae8dedf4-2b6c-4ec5-b96f-307b14eb4d5e)

**Comment by sebastianscatularo** [comment]
Could you please try to reproduce, using a web wallet :)

**Comment by SamantaCasal** [comment]
Using Pera Web, the error is confirmed. FYI: @sebastianscatularo @yuli-ferna 

![Screenshot 2023-12-19 at 11 07 13 AM](https://github.com/XLabs/portal-bridge-ui/assets/69044575/44aebcce-2062-4a8c-bd0e-317470d05b88)

https://github.com/XLabs/portal-bridge-ui/assets/69044575/cdcb5ec3-4af1-41df-9d3a-f6689fce67b6

**Comment by sebastianscatularo** [comment]
@SamantaCasal could you check if you have enough balance to execute the TX using this tool?
-> https://algotools.org/
to verify if it is not this case https://www.reddit.com/r/algorand/comments/12so8ep/error/

**Comment by sebastianscatularo** [comment]
@SamantaCasal please check this [thread](https://xlabs-org.slack.com/archives/C05KPN51PBK/p1701991816696339), there where a discussion regarding a similar issue.

**Comment by SamantaCasal** [comment]
Upadate: 
My balance covers the minimum, but I still see the same error when trying to redeem
![Screenshot 2023-12-19 at 4 29 44 PM](https://github.com/XLabs/portal-bridge-ui/assets/69044575/666f0cd2-be48-479d-8840-502842843189)

![Screenshot 2023-12-19 at 4 34 49 PM](https://github.com/XLabs/portal-bridge-ui/assets/69044575/68542af0-008f-44a4-a769-800e4ad7531d)

**Comment by sebastianscatularo** [comment]
perfect @SamantaCasal, thanks

**Comment by sleepycorgi1** [comment]
Hello! Did we have an update for the user please :)

**Comment by sebastianscatularo** [comment]
@sleepycorgi1 The issue was addressed at [wormhole-sdk ](https://github.com/wormhole-foundation/wormhole/pull/3702), I'll let you know once we cut a new portal version including this.

**Comment by sebastianscatularo** [comment]
@sleepycorgi1 @drisAloma we've deployed a fix for this, could please re-check it

**Comment by sleepycorgi1** [comment]
Hi User is still not able to redeem , please see below 
![Uploading Screen Shot 2024-01-21 at 12.13.52 am.png…]()

**Comment by willis20188** [comment]
> @sleepycorgi1 @drisAloma we've deployed a fix for this, could please re-check it

Another user is facing a similar issue
Ticket 5082
Source chain: BASE
Target chain: ALGO
Tx: https://wormholescan.io/#/tx/0x9600df59136e32ae952031af29d1e5bdaa1faaa1c354e79096f6a0fbd17b0627
![1](https://github.com/XLabs/portal-bridge-ui/assets/83527164/07a509c0-aad3-4ccd-8c4f-6dde3960cdbe)

**Comment by sebastianscatularo** [comment]
we didn't review this again after our last fix attempt, no new updates

**Comment by mliu-xlabs** [comment]
bumping up in priority
