### ISSUE TITLE
[support] Issues sending tokens from Evmos to other chains 

### ISSUE THREAD

**Issue by sleepycorgi1** [XLabs/portal-bridge-ui#654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com

### Operation Details

```markdown
Ticket 2864
- Source Chain:Evmos
- Source Chain Wallet:
- Target Chain: Arbitrum 
- Target Chain Wallet:
- Asset Type:Token 
- Tx:
- Token:ibc/DDB34995CF5E7555A588C74708CD75EEEAF2CD087EEA151F9ED4877B190D4740 (usdc from arbitrum) 
redeemed tx : https://www.mintscan.io/evmos/tx/295C0D989993FA17B428C626262C9D7AFD22F2DE21F11E0FE1B3E1F8B9091A59?height=18177919
```

### Current Behavior

User encounters errors when sending back token from evmos 

### Expected Behavior

User should be able to select the token from token selector and send it back to its original chain 

- it also does not appear on the evmos dashboard to convert from erc to ibc token 

### Steps To Reproduce

1. head to portal bridge
2. connect keplr wallet
3.select token 
4. connect target chain wallet
5. click approve 

### Anything else?

![image](https://github.com/XLabs/portal-bridge-ui/assets/59423378/29292044-c9eb-4897-a192-47a4ce90431c)
![image](https://github.com/XLabs/portal-bridge-ui/assets/59423378/3f3901e5-f6d1-43a1-81e4-44343c840540)
![image](https://github.com/XLabs/portal-bridge-ui/assets/59423378/b037655a-7e74-41fd-a56a-4a291d01b6bd)
![image](https://github.com/XLabs/portal-bridge-ui/assets/59423378/0f044317-46f0-4370-b0ad-89932f76cb01)

**Comment by sleepycorgi1** [comment]
Ticket 2723 
- User having trouble sending wrapped SOL from Evmos back to SOL 
- He has converted the token into IBC on the evmos dashboard, however is encountering errors when trying to send it back
- Has tried with different amounts + solflare/phantom wallet 

![image](https://github.com/XLabs/portal-bridge-ui/assets/59423378/7bdc85ba-27a1-4e6e-8272-fa96701eb5c2)
![image](https://github.com/XLabs/portal-bridge-ui/assets/59423378/1a122a3c-00af-4a77-a04d-f6a95f829e70)
![image](https://github.com/XLabs/portal-bridge-ui/assets/59423378/19218707-d2f2-4b0e-b9d6-1e66a12e65e4)

**Comment by sleepycorgi1** [comment]
Ticket 2908 
- User trying to send WBTC from evmos to ethereum 
- THey have already converted from erc to ibc token in the evmos dashboard 
<img width="749" alt="Screen Shot 2024-01-09 at 4 26 41 pm" src="https://github.com/XLabs/portal-bridge-ui/assets/59423378/b0663dc7-6477-4f3d-9bcd-4ab54e17f0dc">
<img width="762" alt="Screen Shot 2024-01-09 at 4 26 57 pm" src="https://github.com/XLabs/portal-bridge-ui/assets/59423378/488a52fb-20ac-45d7-aefb-2491f61ba82d">

<img width="787" alt="Screen Shot 2024-01-09 at 4 26 31 pm" src="https://github.com/XLabs/portal-bridge-ui/assets/59423378/01687cac-c6ec-4bb0-8270-7e48f81adcb7">

**Comment by Dahtank** [comment]
Ticket 3210
User unable to bridge back wFTM to FTM chain because of error when trying to use Portalbridge
The workaround Portfolio doesn't show wFTM
- Source Chain: FTM
- Source Wallet Address: 0x4333e265a5640af11b8194cf75fe4defafdec776
- Target Chain: Evmos
- Target Wallet Address: evmos1juxj3zgmr4kf3m35puns5yvmykynslgashe922
- Asset Type: wFTM
- Tx: 0xb3d3f2c2ced1cd85f2e88601c116e98379e1582f7f77af04f7eaed821a528e34
![image](https://github.com/XLabs/portal-bridge-ui/assets/141799468/0d74173d-01a9-4ef5-b63f-95a48b6c0047)

**Comment by sebastianscatularo** [comment]
@sleepycorgi1 @Dahtank could you re-check this, we've deployed a fix for them, and let us know if any new issue

**Comment by sleepycorgi1** [comment]
@sebastianscatularo theyre still having the same error .

ticket 2908 :
<img width="765" alt="Screen Shot 2024-01-22 at 5 37 55 pm" src="https://github.com/XLabs/portal-bridge-ui/assets/59423378/d9554e2d-8b80-4e6d-987d-199d8c25d7ae">

**Comment by sleepycorgi1** [comment]
Console logs for ticket 2723:
![image](https://github.com/XLabs/portal-bridge-ui/assets/59423378/1c9cbfc3-4b0e-4eef-ac69-54d28e0838e6)

**Comment by sebastianscatularo** [comment]
@sleepycorgi1 sadly those errors are expected at portal, until we fix some of them. and are not the root cause of not being able to bridge

**Comment by willis20188** [comment]
Ticket 6294
facing a similar issue
Source Chain: Evmos
Target Chain: Solana
<img width="690" alt="11" src="https://github.com/XLabs/portal-bridge-ui/assets/83527164/5b3fa6b6-cce2-4033-acd4-d14f0923f840">
<img width="1082" alt="12" src="https://github.com/XLabs/portal-bridge-ui/assets/83527164/baa693fb-efc7-4c3e-8ce6-c38c53e67b27">

**Comment by Dahtank** [comment]
Ticket 6294 User managed to send 0.1 USDC(sol) from Evmos to Kujira then back to Solana chain
But after that another error for USDC(sol) from Evmos to Kujira 
![image](https://github.com/XLabs/portal-bridge-ui/assets/141799468/f76a0db2-4769-4b9a-9293-07166c69ebbc)

**Comment by Dahtank** [comment]
Ticket 7754 Evmos -> Solana
Error with Transfer, please try again
Token: wBTC 
![image](https://github.com/XLabs/portal-bridge-ui/assets/141799468/a17bf70f-93e8-40c6-9ccb-ad682467766a)

**Comment by AigaD** [comment]
Tested from: 
https://portalbridge.com/ - Tested NOK
https://wormhole-connect-mainnet.netlify.app/# - Tested OK
Actual result: First transaction from Evmos fails with reason `TypeError: Failed to fetch`, starting the same transaction for the second time (clicking on Approve and proceed with transaction button) the transaction is started.

Attachment:

https://github.com/XLabs/portal-bridge-ui/assets/91047061/5829c63e-23c9-4ef6-bd84-43f22d8c2223

![Screenshot 2024-03-05 at 10 00 16](https://github.com/XLabs/portal-bridge-ui/assets/91047061/3e89a510-4704-4bac-8a6b-aefbb8a3517a)

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/ [Mainnet] when sending 0.001 WFTM from Evmos (Leap) to Kujira (Leap). 

Error appears after clicking on "Approve and proceed with transaction" button:
```
TypeError: Failed to fetch
    at ik.getAccount (cosmos-nV16HvSD-CyAO9FXW.js:112:136558)
    at ik.signTransaction (cosmos-nV16HvSD-CyAO9FXW.js:112:137214)
    at async ik.signAndSendTransaction (cosmos-nV16HvSD-CyAO9FXW.js:112:137776)
    at async Dk (cosmos-nV16HvSD-CyAO9FXW.js:112:138489)
    at async signAndSendTransaction (pb-index.js:490:769495)
    at async Operator.send (pb-index.js:496:81757)
    at async Object.Sr [as onClick] (pb-index.js:692:32413)
```

![image](https://github.com/XLabs/portal-bridge-ui/assets/10746654/a92664f7-b936-4d6d-906b-37e8c29f2b93)
