### ISSUE TITLE
[support] Cannot resume transfer from KUJIRA and OSMOSIS<ticket-8936 & 8502>

### ISSUE THREAD

**Issue by drisAloma** [XLabs/portal-bridge-ui#794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com

### Operation Details

```markdown
- Source Chain: Kujira
- Source Chain Wallet: Kepler/Leap
- Target Chain:Solana
- Target Chain Wallet: Phantom 
- Asset Type: Token 
- Tx:https://finder.kujira.network/kaiyo-1/tx/793C32AC38C331837274F0097213DEF34286743798323CCD54A05B23F846CC18
```

### Current Behavior

![IMG_20240321_182205](https://github.com/XLabs/portal-bridge-ui/assets/64994788/c6acd584-536a-4306-8ef8-03e3af718ea6)

### Expected Behavior

Find and resume transaction then proceed to claim on Solana.

### Steps To Reproduce

1. Go to https://www.portalbridge.com
2. Click on Resume on the lower left corner.
3. Choose KUJIRA as Network 
4. Paste in the transaction hash; 793C32AC38C331837274F0097213DEF34286743798323CCD54A05B23F846CC18

### Anything else?

![IMG_20240321_182441](https://github.com/XLabs/portal-bridge-ui/assets/64994788/6373c2d6-e5a4-4218-b8fa-f8059ebf515f)

**Comment by drisAloma** [comment]
Similar issue (ticket-8502)
Source Chain: OSMOSIS
Source Wallet Address: osmo1d9avhj95crystrqgh4p749l2eydpl66t5xywuw
Target Chain: SOLANA
Target Wallet Address: 3bgVfZuPJP25tNuZEz2ibXVM3uUbpMZxxg1oQAuH2baz
Asset Type: WSOL
Tx: https://www.mintscan.io/osmosis/tx/42151A2A15F16512E66326746AF7B3CFB5BD1A676A0A0CC97D48F8CF2F961007

**Comment by drisAloma** [comment]
Similar issue, ticket-9289, the console log is quite different though 
Source Chain: INJECTIVE 
Target Chain: SOLANA
Tx: https://explorer.injective.network/transaction/82E6CC12A000A7EA11F83F450CDE2070D773AB5A4C3AD7E976C0AF610CC2465D/
![IMG_20240321_183805](https://github.com/XLabs/portal-bridge-ui/assets/64994788/7e22decc-f2ec-4720-99b3-5ce01d4ad5ac)
![IMG_20240321_183517](https://github.com/XLabs/portal-bridge-ui/assets/64994788/40d8a0e4-6762-48be-83d8-0601f2a5286b)

**Comment by drisAloma** [comment]
Tried the redeem workflow on the advanced bridge page
![IMG_20240321_183348](https://github.com/XLabs/portal-bridge-ui/assets/64994788/80c3d775-2fce-49ee-a100-cb342f4947ff)

**Comment by SamantaCasal** [comment]
Fixed Injective case: https://wormholescan.io/#/tx/82E6CC12A000A7EA11F83F450CDE2070D773AB5A4C3AD7E976C0AF610CC2465D

**Comment by drisAloma** [comment]
Hello @SamantaCasal 
It is still not returning the transaction on the UI
![IMG_20240327_172532](https://github.com/XLabs/portal-bridge-ui/assets/64994788/8b66ce61-2ce3-4f01-9672-2cd676686229)
